Documentation update (#434)
* 🚧 use myst-nb (which has myst-parser as dependency), add all nb without execution

* :art: intersphinx biopython and removing non-used markdowns

* :sparkles: update build script of website

* :art: swap to sphinx-book-theme

* :art: hide toctree toc on landing page

* :sparkles: execute all notebooks in notebooks

* :memo: cookbook nb does not work

Error:
'Dseqrecord' object has no attribute 'cseguid'

* :art: fix headings in example nb

* 🔧 run poetry lock (as suggested by CLI)

* :bug: try to make sphinx-apidoc work

* :bug: run through poetry

- alternatively activate the environment: poetry env use

* :bug: remove removed dependency from extensions list